theme: jekyll-theme-cayman
title: COMP0016 - Development Blog
description: |
  - Arthur Murray Dance Content Platform
  - Team 14 - Periklis Ntinos, WeiJian Xu, Leon Yao

author: Periklis Ntinos, WeiJian Xu, Leon Yao
